# Export merged dataset from 3 different meteorological datasets
#  used to calculate CH4 emissions
# May 26th, 2021 by John C. Lin (John.Lin@utah.edu)

###################
obsdir <- "/uufs/chpc.utah.edu/common/home/lin-group4/jcl/SimCity"
mettypes <- c("HRRR","NAM12","WRF27")
###################

#---------- export observational datasets ----------#
sites <- c("FRU","HPL","CSP")
YEARs <- 2015:2020
tracer <- "CH4"
for(yy in 1:length(YEARs)){
  YEAR <- YEARs[yy]
  # generated by "/uufs/chpc.utah.edu/common/home/lin-group4/jcl/SimCity/extract_hrly_subsetsites.r"
  outputname<-paste("UUCON_",tracer,"_",paste0(sites,collapse="_"),"_hrly_",YEAR,".csv",sep="")  
  file.copy(from=file.path(obsdir,outputname),to=file.path("./",outputname))
} # for(yy in 1:length(YEARs)){
system(paste0("rename UUCON_",tracer," UINTA_",tracer," UINTA_*.csv"))
system(paste0("tar cvf ~/public_html/Exchange/UINTA_",tracer,".tar UINTA_",tracer,"*.csv"))

#---------- export output from Fch4_simple.r ----------#
SITE <- "HPL"
for(mm in 1:length(mettypes)){
  mettype <- mettypes[mm]
  dat <- readRDS(paste0("Fch4_",SITE,"_",mettype,".rds"))
  CSVfile <- paste0("Fch4_",SITE,"_",mettype,".csv")
  write.csv(dat,file=CSVfile,row.names=FALSE)
  print(paste(CSVfile,"written out"))
} # for(mm in 1:length(mettypes)){
system(paste0("tar cvf ~/public_html/Exchange/Fch4.tar Fch4_",SITE,"_*.csv"))

