# Simple STILT analyses of Uinta Basin methane emissions
# Idea is to calculate AFTERNOON enhancements (CH4_HPL - CH4_FRU), & then divide by total footprint strength:
#   F_CH4 = (CH4_HPL - CH4_FRU)/sum(foot_i,j)
#
# Based on 'Fch4_simpleV8.r', but plot results from MULTIPLE MET FIILES driving STILT
# V2(210522): for paper submission, add Karion number, change oil/gas colors, and remove some of the infoormational labels
# May 3rd, 2021 by John C. Lin (John.Lin@utah.edu)

require(ncdf4); require(fields); require(geosphere)
####################
YEARs <- 2015:2020
MONsub <- 4:9 #subset of months to calculate fluxes and leak rates
HRs<-20:23  #[UTC]  only analyze afternoon hours, following Foster papers
#HRs<-17:23  #[UTC]  only analyze afternoon hours, following Foster papers
SITE<-"HPL" #HPL is site to focus on for calculating long-term F_CH4
#SITE<-"ROO" 
#SITE<-"CSP" 
if(SITE=="CSP")YEARs <- c(2016,2019,2020)
if(SITE=="ROO")YEARs <- 2015:2019

mettypes <- c("HRRR","NAM12","WRF27")

XLIMS<-c(-110.6,-109)   # lon range of Uinta Basin
YLIMS<-c(39.9,40.5)     # lat range of Uinta Basin


Nday.min <- 10          # minimum days necessary for a monthly average to be retained (otherwise assigned NA)
fillFRU.TF <- TRUE      # fill in gaps in background (FRU) time series?
filterUV.TF <- TRUE     # filter times based on U/V (filter out times when HRRR is off--i.e., large transport errors) ?
CH4.VOLFRAC <- 0.89     # volume fraction of CH4 in natural gas of 0.89 [Karion et al. 2013]

col.gas <- "#B91C1C"  # red
col.oil <- "#1D4ED8"  # blue
col.tot <- "black"    # total/black
####################


if(SITE=="HPL"){LAT <- 40.1434; LON <- -109.4680; zagl <- 4.06; WINDsite <- "UBHSP"; WINDsite.2015 <- "A1633"}  # UBHSP site not available in 2015, so use A1633 (RedWash) site instead in 2015
if(SITE=="ROO"){LAT <- 40.2941; LON <- -110.0090; zagl <- 4.06; WINDsite <- "QRS"}
if(SITE=="CSP"){LAT <- 40.0509; LON <- -110.0194; zagl <- 4.06; WINDsite <- "UBCSP"}

# Function that converts from natural gas volume in thousands of [MCF]  to [kg of CH4]
MCF2kg <- function(MCF,CH4.VOLFRAC=0.89){
NatGas<-MCF*CH4.VOLFRAC   #[MCF natural gas] => [MCF CH4], using volume fraction of CH4 in natural gas of 0.89 [Karion et al. 2013]
XLIMS<-c(-110.6,-109)   # lon range of Uinta Basin
YLIMS<-c(39.9,40.5)     # lat range of Uinta Basin

NatGas<-NatGas*1000   #[MCF CH4] => [ft^3 CH4]
  NatGas<-NatGas*0.0283 #[ft^3 CH4] => [m^3 CH4]
  R.CH4<-8.3143*1000/16.043   #Ideal Gas constant of CH4 [J/K/kg]: (Rg/mCH4), where Rg is universal gas constant and mCH4 is molar mass of CH4
  rho.CH4<-(101300)/(R.CH4*288.7)   #density of CH4 [kg/m3], using P=101.3kPa and T=288.7K [Karion et al. 2013]
  NatGas<-NatGas*rho.CH4 #[m^3 CH4] => [kg CH4]
  return(NatGas)
} # MCF2kg <- function(MCF,CH4.VOLFRAC=0.89){


#########################################################
# Calculate average gridcell area 
dx1<-distHaversine(c(XLIMS[1],YLIMS[1]),c(XLIMS[2],YLIMS[1]))   #[m]
dx2<-distHaversine(c(XLIMS[1],YLIMS[2]),c(XLIMS[2],YLIMS[2]))   #[m]
dy1<-distHaversine(c(XLIMS[1],YLIMS[1]),c(XLIMS[1],YLIMS[2]))   #[m]
dy2<-distHaversine(c(XLIMS[2],YLIMS[1]),c(XLIMS[2],YLIMS[2]))   #[m]
AREA<-mean(c(dx1,dx2))*mean(c(dy1,dy2))   #[m^2]

for(i in 1:length(mettypes)){
  #mettype <- "HRRR"
  mettype <- mettypes[i]
  resultname<-paste("Fch4_",SITE,"_daily_",mettype,".rds",sep="")

#########################################################
# Read in data generated by "Fch4_simple.r" and calculate monthly-averaged emissions
dat<-readRDS(resultname)
#plot time series of monthly averages
Time.mon<-format(dat[,"Time"],format="%Y%m")
Fch4.sum<-tapply(dat[,"Fch4.sum"],Time.mon,mean,na.rm=T)
Fch4.basin<-tapply(dat[,"Fch4.basin"],Time.mon,mean,na.rm=T)
Fch4.sum[is.nan(Fch4.sum)] <- NA; Fch4.basin[is.nan(Fch4.basin)] <- NA
#  calculate how many valid days there are in each month
Ntmp <- tapply(dat[!is.na(dat$Fch4.basin),"Fch4.basin"],Time.mon[!is.na(dat$Fch4.basin)],length)
N <- Fch4.basin; N[1:length(N)] <- NA;  N[names(Ntmp)] <- Ntmp
Fch4.basin[N<Nday.min] <- NA   # assign NA if # of valid days less than minimum
Fch4.sum[N<Nday.min] <- NA   # assign NA if # of valid days less than minimum
Fch4.basin.sd<-tapply(dat[,"Fch4.basin"],Time.mon,sd,na.rm=T)
Fch4.basin.sd[N<Nday.min] <- NA   # assign NA if # of valid days less than minimum



#########################################################
# Calculate emissions at Uinta Basin scale
Ech4.sum<-Fch4.sum*AREA*3600  #[umole/m2/s]=>[umole/hr]
Ech4.sum<-Ech4.sum*(12.0111+4*1.008)*1E-6/1000/(1000)  #[umole/hr]=>[10^3 kg/hr]
Ech4.basin<-Fch4.basin*AREA*3600  #[umole/m2/s]=>[umole/hr]
Ech4.basin<-Ech4.basin*(12.0111+4*1.008)*1E-6/1000/(1000)  #[umole/hr]=>[10^3 kg/hr]
Ech4.basin.sd<-Fch4.basin.sd*AREA*3600  #[umole/m2/s]=>[umole/hr]
Ech4.basin.sd<-Ech4.basin.sd*(12.0111+4*1.008)*1E-6/1000/(1000)  #[umole/hr]=>[10^3 kg/hr]



#########################################################
#  Calculate annual emissions
dat<-readRDS(resultname)
isNA<-is.na(dat[,"Fch4.basin"]); dat2<-dat[!isNA,]
dat<-dat2[as.numeric(substring(dat2[,"YYYYMMDD"],5,6))%in%MONsub,]
#plot time series of monthly averages
Time.mon<-format(dat[,"Time"],format="%Y%m")
Fch4.basin<-tapply(dat[,"Fch4.basin"],Time.mon,mean,na.rm=T)
Fch4.basin[is.nan(Fch4.basin)] <- NA
#  calculate how many valid days there are in each month
Ntmp <- tapply(dat[!is.na(dat$Fch4.basin),"Fch4.basin"],Time.mon[!is.na(dat$Fch4.basin)],length)
N <- Fch4.basin; N[1:length(N)] <- NA;  N[names(Ntmp)] <- Ntmp
Fch4.basin[N<Nday.min] <- NA   # assign NA if # of valid days less than minimum
YYYY<-substring(names(Fch4.basin),1,4)
#calculate error bars, sample numbers
NN<-tapply(YYYY,YYYY,length)
CONV<-AREA*3600*(12.0111+4*1.008)*1E-6/1000/(1000)  #[umole/m2/s]=>[10^3 kg/hr]
Fch4.yr<-tapply(Fch4.basin,YYYY,mean,na.rm=T)
Fch4.yr.sd<-tapply(Fch4.basin,YYYY,sd,na.rm=T)
Ech4.yr<-Fch4.yr*CONV
Ech4.yr.sd<-Fch4.yr.sd*CONV
Ech4.yr.stderr<-Ech4.yr.sd/sqrt(NN)


#########################################################
#  Calculatet monthly Basin-Wide Emissions 
YYYYMM<-names(Ech4.basin)
frYr<-as.numeric(substring(YYYYMM,1,4))+(as.numeric(substring(YYYYMM,5,6))-0.5)/12
SEL<-as.numeric(substring(YYYYMM,5,6))%in%MONsub
# calculate error bars, sample numbers
dat<-readRDS(resultname)
isNA<-is.na(dat[,"Fch4.basin"]); dat2<-dat[!isNA,]
YYYYMM<-substring(dat2[,"YYYYMMDD"],1,6)
NN<-tapply(YYYYMM,YYYYMM,length)
Ech4.basin.stderr<-Ech4.basin.sd
Ech4.basin.stderr[names(Ech4.basin.stderr)]<-Ech4.basin.sd[names(Ech4.basin.stderr)]/sqrt(NN[names(Ech4.basin.stderr)])
Ech4.basin[names(NN)][NN<Nday.min]<-NA   #too small a sample size, so assign NA
XMAIN <- paste0(SITE,";  UThrs: ",paste(HRs,collapse=","),"\nfillFRU.TF=",fillFRU.TF,";  filterUV.TF=",filterUV.TF)
XSUB <- paste0("mettype=",mettype,";  Mons: ",paste(MONsub,collapse=","),";  Nday.min=",Nday.min)
#dev.new();par(cex.axis=1.3,cex.lab=1.3,cex.main=1.3,mar=c(5,5,4,5))
#plot(frYr[SEL],Ech4.basin[SEL],main=XMAIN,sub=XSUB,pch=16,lwd=2,
#     xlab="Year",ylab="Emissions of CH4 from Uinta Basin [10^3 kg/hr]",type="p",col="gray")
#abline(h=55,col="red",lty=2,lwd=2) #Uinta Basin-wide CH4 emissions [10^3 kg/hr], as reported by Karion et al. [2013]
#segments(x0=frYr[SEL],y0=Ech4.basin[SEL]-Ech4.basin.stderr[SEL],x1=frYr[SEL],y1=Ech4.basin[SEL]+Ech4.basin.stderr[SEL],col="gray")


#########################################################
#  Calculate emissions as % of CH4 from Natural Gas PRODUCTION during SELECTED MONTHS, instead of using ANNUAL PRODUCTION values
#convert units of natural gas & oil production
tmp<-readRDS("State_of_Utah_oil_gas_DATA/gas.oil.production_monthly.rds")
counties<-unique(tmp$County)
NatGas <- tapply(tmp[,"Natural.Gas..MCF."],list(tmp[,"Time"]),sum,na.rm=TRUE)  #sum monthly values over counties
NatGas <- MCF2kg(MCF=NatGas,CH4.VOLFRAC=CH4.VOLFRAC)  #[MCF Natural Gas per Month] => [kg CH4 per Month]
NatGas <- NatGas/1000  #[kg CH4 per Month] => [10^3 kg CH4 per Month]
NatGas <- NatGas/(24*(365/12)) # [10^3 kg CH4 per Month] => [10^3 kg CH4 per Hour]
YYYYMM <- paste0(substring(names(NatGas),1,4),substring(names(NatGas),6,7))
names(NatGas) <- YYYYMM
NatGas <- NatGas[names(Ech4.basin)]
YYYYMMsel <- paste0(rep(YEARs,each=length(MONsub)),rep(formatC(MONsub,width=2,flag="0"),length(YEARs)))
NatGas <- NatGas[YYYYMMsel]
#  average production during selected months each year
NatGas.yr <- tapply(NatGas,substring(names(NatGas),1,4),mean,na.rm=T)   # [10^3 kg CH4/Hr]
frYr<-as.numeric(names(NatGas.yr))+0.5
# Ech4.yr is in units of [10^3 kg CH4/hr]
Ech4.yr.perc <- Ech4.yr*100/NatGas.yr
Ech4.yr.perc.stderr<-100*Ech4.yr.stderr/NatGas.yr   #stderr as % of CH4 in natural gas production


#XMAIN <- paste0(SITE,";  UThrs: ",paste(HRs,collapse=","),"\nfillFRU.TF=",fillFRU.TF,";  filterUV.TF=",filterUV.TF)
#XSUB <- paste0("mettype=",mettype,"; Mons: ",paste(MONsub,collapse=","),";  Nday.min=",Nday.min,";  CH4.VOLFRAC=",CH4.VOLFRAC)
#dev.new();par(cex.axis=1.3,cex.lab=1.3,cex.main=1.3,mar=c(5,5,4,5))
#ylims<-c(0,10)
#plot(frYr,Ech4.yr.perc,main=XMAIN,sub=XSUB,pch=16,type="o",
#     xlab="Year",ylab="Emissions of CH4 from Uinta Basin [% Production]",ylim=ylims)
#segments(x0=frYr,y0=Ech4.yr.perc-Ech4.yr.perc.stderr,x1=frYr,y1=Ech4.yr.perc+Ech4.yr.perc.stderr)
#dev.copy(png,"Fch4_simple_9.png");dev.off()

#########################################################
# Calculate Energy-Normalized Methane Average (ENMA) emissions--i.e., CH4 emissions as % of total NatGas+Oil production of energy 
tmp<-readRDS("State_of_Utah_oil_gas_DATA/gas.oil.production_monthly.rds")
counties<-unique(tmp$County)
Oil <- tapply(tmp[,"Oil..BBLs."],list(tmp[,"Time"]),sum,na.rm=TRUE)  #sum monthly values over counties
Oil.BTU <- Oil * 5.8E6   # oil production in energy units [Barrels/Month] => [BTU/Month]; from Robertson et al. (2017)
NatGas <- tapply(tmp[,"Natural.Gas..MCF."],list(tmp[,"Time"]),sum,na.rm=TRUE)  #sum monthly values over counties
NatGas.BTU <- NatGas*1E6 # gas productioon in energy units [MCF Natural Gas/Month] => {BTU/Month];  from Robertson et al. (2017)  
#  select subset based on Year/Month
YYYYMMsel <- paste0(rep(YEARs,each=length(MONsub)),"-",rep(formatC(MONsub,width=2,flag="0"),length(YEARs)),"-01")
NatGas.BTU <- NatGas.BTU[YYYYMMsel] ; Oil.BTU <- Oil.BTU[YYYYMMsel] 
# average each year
NatGas.BTU.monave <- tapply(NatGas.BTU,substring(names(NatGas.BTU),1,4),mean,na.rm=T)
Oil.BTU.monave <- tapply(Oil.BTU,substring(names(Oil.BTU),1,4),mean,na.rm=T)
NatGas.BTU.hr <- NatGas.BTU.monave/(24*(365/12))  # [BTU per Month] => [BTU per Hour]
Oil.BTU.hr <- Oil.BTU.monave/(24*(365/12))        # [BTU per Month] => [BTU per Hour]
#  convert methane emissions back from [10^3 kg CH4 per Hour] => [MCF (thousands of cubic feet) natural gas/Year]
Egas <- data.frame(Ech4.yr,Ech4.yr.stderr) # [10^3 kg CH4/hr]
Egas <- Egas*1000                          # [10^3 kg CH4/hr] => [kg CH4/hr]
CONV <- MCF2kg(MCF=1,CH4.VOLFRAC=CH4.VOLFRAC)  #[MCF Natural Gas] => [kg CH4] conversion factor
Egas <- Egas/CONV                          # [kg CH4/hr] => [MCF Natural Gas/hr]
Egas <- Egas*CH4.VOLFRAC                   # [MCF Natural Gas/hr] => [MCF methane/hr]
Egas.BTU.hr <- Egas * 1E6   # gas emissions in energy units [MCF Natural Gas/hr] OR [MCF methane/hr]=> [BTU/hr] from Robertson et al. (2017)
ENBA <- 100*Egas.BTU.hr/(Oil.BTU.hr+NatGas.BTU.hr)

#########################################################
# Save all of the relevant objects as a LIST for each met type
result <- list(Ech4.basin=Ech4.basin,Ech4.basin.sd=Ech4.basin.sd,Ech4.basin.stderr=Ech4.basin.stderr,
               Ech4.yr=Ech4.yr,Ech4.yr.sd=Ech4.yr.sd,Echr.yr.stderr=Ech4.yr.stderr,
               Ech4.yr.perc=Ech4.yr.perc,Ech4.yr.perc.stderr,ENBA=ENBA)
finalresultfile <- paste0(mettype,".rds")
saveRDS(result,file=finalresultfile)
print(paste(finalresultfile,"generated"))

} # for(i in 1:length(mettypes)){


#########################################################
# Plot annual emissions
dev.new();par(cex.axis=1.5,cex.lab=1.5,cex.main=1.6,mar=c(5,5,4,3))
#XMAIN <- paste0("CH4 Emissions from Uinta Basin\nUThrs: ",paste(HRs,collapse=","))
#XSUB <- paste0("Mons: ",paste(MONsub,collapse=","),";  Nday.min=",Nday.min)
XMAIN <- expression("CH"[4]*" Emissions from Uinta Basin")  
xlims <- c(2012,2021)
XSUB <- ""
plot(0,0,main=XMAIN,sub=XSUB,pch=16,type="o",xlim=xlims,
     ylim=c(18,60),xlab="Year",ylab=expression(paste("CH"[4]," Emissions [10"^3," kg hr"^-1,"]")))
Ech4.yr.sum <- 0
for(mm in 1:length(mettypes)){
  mettype <- mettypes[mm]
  dat <- readRDS(paste0(mettype,".rds"))
  Ech4.yr <- dat$Ech4.yr
  YYYY<-names(Ech4.yr)
  frYr<-as.numeric(substring(YYYY,1,4))+0.5
  lines(frYr,Ech4.yr,lty=mm+1,lwd=2)
  #segments(x0=frYr,y0=Ech4.yr-Ech4.yr.stderr,x1=frYr,y1=Ech4.yr+Ech4.yr.stderr)
  Ech4.yr.sum <- Ech4.yr.sum + Ech4.yr
} # for(mm in 1:length(mettypes)){
axis(1,at=seq(xlims[1],xlims[2],1),cex=1.5,labels=FALSE)
Ech4.yr.ave <- Ech4.yr.sum/length(mettypes)
lines(frYr,Ech4.yr.ave,lty=1,lwd=4)
#  add Karion et al. [2013] emissions result based on Feb. 2012 observations
x.Karion <- 2012 + 1.5/12; y.Karion <- 55; y.sigma <- 15
points(x.Karion,y.Karion,pch=17,cex=1.5)
arrows(x0=x.Karion,y0=y.Karion-y.sigma,x1=x.Karion,y1=y.Karion+y.sigma,code=3,angle=90,length=0.1,lwd=2)
text(x=2013.5,y=y.Karion,"Karion et al.\n(2013)",cex=1.5)
legend("topright",c("Model Mean",mettypes),lty=1:(length(mettypes)+1),lwd=c(4,rep(2,length(mettypes))),cex=1.3)
dev.copy(png,"Fch4_annual_ALLmet.png");dev.off()


dev.new();par(cex.axis=1.5,cex.lab=1.5,cex.main=1.5,mar=c(5,6,5,3))
ylims <- c(1,10)
xlims <- c(2012,2021)
#XMAIN <- paste0("CH4 Emissions as % of Natural Gas Production or\n Total Energy Production from Uinta Basin\nUThrs: ",paste(HRs,collapse=","))
#XSUB <- paste0("Mons: ",paste(MONsub,collapse=","),";  Nday.min=",Nday.min)
XMAIN <- expression(paste("CH"[4]," Emissions as % of Production from Uinta Basin"))  
XSUB <- ""
plot(0,0,main=XMAIN,sub=XSUB,pch=16,,
     xlab="Year",ylab="% NatGas Production or\n% Energy Production",xlim=xlims,ylim=ylims)
Ech4.yr.perc.sum <- 0
ENBA.sum <- 0
for(mm in 1:length(mettypes)){
  mettype <- mettypes[mm]
  dat <- readRDS(paste0(mettype,".rds"))
  Ech4.yr.perc <- dat$Ech4.yr.perc
  print(paste("----------",mettype,"%NatGas Prod----------"))
  print(paste(round(mean(Ech4.yr.perc),2),"+/-",round(sd(Ech4.yr.perc),2),"[%]"))
  ENBA <- dat$ENBA
  YYYY<-names(Ech4.yr.perc)
  frYr<-as.numeric(substring(YYYY,1,4))+0.5
  lines(frYr,Ech4.yr.perc,lty=mm+1,lwd=2,col=col.gas)
  #segments(x0=frYr,y0=Ech4.yr.perc-Ech4.yr.perc.stderr,x1=frYr,y1=Ech4.yr.perc+Ech4.yr.perc.stderr)
  lines(frYr,ENBA$Ech4.yr,,col=col.tot,lty=mm+1,lwd=2)
  #segments(x0=frYr,y0=ENBA$Ech4.yr-ENBA$Ech4.yr.stderr,x1=frYr,y1=ENBA$Ech4.yr+ENBA$Ech4.yr.stderr,col="darkgray")
  Ech4.yr.perc.sum <- Ech4.yr.perc.sum + Ech4.yr.perc
  ENBA.sum <- ENBA.sum + ENBA$Ech4.yr
} # for(mm in 1:length(mettypes)){
axis(1,at=seq(xlims[1],xlims[2],1),cex=1.5,labels=FALSE)
Ech4.yr.perc.ave <- Ech4.yr.perc.sum/length(mettypes)
ENBA.ave <- ENBA.sum/length(mettypes)
lines(frYr,Ech4.yr.perc.ave,,col=col.gas,lty=1,lwd=4)
lines(frYr,ENBA.ave,,col=col.tot,lty=1,lwd=4)
#  add Karion et al. [2013] leakage rate result based on Feb. 2012 observations
x.Karion <- 2012 + 1.5/12; y.Karion <- mean(c(6.2,11.7)); y.sigma <- y.Karion-6.2
points(x.Karion,y.Karion,pch=17,cex=1.5,col=col.gas)
arrows(x0=x.Karion,y0=y.Karion-y.sigma,x1=x.Karion,y1=y.Karion+y.sigma,code=3,angle=90,length=0.1,lwd=2,col=col.gas)
text(x=2013.5,y=y.Karion,"Karion et al.\n(2013)",cex=1.5,col=col.gas)
legend("bottomleft",c("Model Mean",mettypes),lty=1:(length(mettypes)+1),lwd=c(4,rep(2,length(mettypes))),cex=1.3,bty="n")
legend(x=2015.5,y=3,legend=c("% NatGas Production","% Energy Production\n(NatGas+Oil)"),
       col=c(col.gas,col.tot),lty=1,lwd=2,text.col=c(col.gas,col.tot),cex=1.3,bty="n")
dev.copy(png,"Fch4_percGasOil_ALLmet.png");dev.off()


